services:
  android:
    image: storytellerf/android-in-docker:snapshot
    ports:
      - "6080:6080" # noVNC web interface
      - "5901:5901" # VNC direct connection
      - "5555:5555" # ADB
      - "4723:4723" # Appium
    environment:
      - VNC_GEOMETRY=1920x1080
      - VNC_DEPTH=24
    env_file:
      - .env
    volumes:
      - ./logs:${CONTAINER_HOME:-/home/debian}/log/supervisor
      - avd_data:${CONTAINER_HOME:-/home/debian}/.android/avd
      - sdk_data:${CONTAINER_HOME:-/home/debian}/Android/Sdk
      - bash_history:${CONTAINER_HOME:-/home/debian}/.android-in-docker/.bash_history
    shm_size: '2gb' # Allocate more shared memory
    restart: "unless-stopped"

volumes:
  avd_data:
  sdk_data:
    external: true
  bash_history:
