#!/bin/bash

# Advanced script to generate comprehensive dependency documentation
# This script extracts and formats dependency information from apt

OUTPUT_FILE="DEPENDENCIES.md"
PACKAGES=(
    "dbus-x11"
    "supervisor"
    "tightvncserver"
    "xfce4"
    "xfce4-goodies"
    "novnc"
    "openjdk-21-jdk"
    "wget"
    "unzip"
    "qemu-kvm"
    "elinks"
    "locales"
    "npm"
    "sudo"
)

# Function to extract and format dependency information
get_package_deps() {
    local pkg=$1
    apt depends "$pkg" 2>/dev/null
}

# Function to extract depends (required dependencies)
get_depends() {
    local pkg=$1
    apt depends "$pkg" 2>/dev/null | grep "^\s*$pkg" | grep -v "Depends:" | sed 's/^\s*|\s*//' | sort -u
}

# Function to extract recommends
get_recommends() {
    local pkg=$1
    apt depends "$pkg" 2>/dev/null | grep -A 5000 "Recommends:" | grep "^\s*$pkg" | sed 's/^\s*|\s*//' | sort -u
}

# Function to extract suggests
get_suggests() {
    local pkg=$1
    apt depends "$pkg" 2>/dev/null | grep -A 5000 "Suggests:" | grep "^\s*$pkg" | sed 's/^\s*|\s*//' | sort -u
}

# Generate markdown header
generate_header() {
    cat > "$OUTPUT_FILE" << EOF
# Docker Image Package Dependencies Documentation

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')

This document provides comprehensive dependency information for all packages installed in the Android-in-Docker image.

## Table of Contents

1. [Overview](#overview)
2. [Direct Dependencies](#direct-dependencies)
3. [Packages Details](#packages-details)

---

## Overview

### Primary Packages

The following packages are directly installed in the Dockerfile:

EOF

    for pkg in "${PACKAGES[@]}"; do
        echo "- \`$pkg\`" >> "$OUTPUT_FILE"
    done
    
    cat >> "$OUTPUT_FILE" << EOF

---

## Direct Dependencies

### Summary Table

| Package | Dependencies | Recommends | Suggests |
|---------|--------------|------------|----------|
EOF
}

# Function to add package details
add_package_section() {
    local pkg=$1
    
    cat >> "$OUTPUT_FILE" << EOF

### $pkg

**Package Type**: Primary Install

**Description**:
EOF
    
    apt-cache show "$pkg" 2>/dev/null | grep "^Description:" | head -1 | sed 's/^Description: //' >> "$OUTPUT_FILE"
    
    cat >> "$OUTPUT_FILE" << EOF

#### Required Dependencies

\`\`\`
EOF
    
    apt depends "$pkg" 2>/dev/null | grep "^\s*$pkg" | grep -v "Depends:" | head -20 >> "$OUTPUT_FILE"
    
    cat >> "$OUTPUT_FILE" << EOF
\`\`\`

#### Recommended Packages

\`\`\`
EOF
    
    apt recommends "$pkg" 2>/dev/null | head -10 >> "$OUTPUT_FILE" || echo "(None)" >> "$OUTPUT_FILE"
    
    cat >> "$OUTPUT_FILE" << EOF
\`\`\`

#### Suggested Packages

\`\`\`
EOF
    
    apt suggests "$pkg" 2>/dev/null | head -10 >> "$OUTPUT_FILE" || echo "(None)" >> "$OUTPUT_FILE"
    
    cat >> "$OUTPUT_FILE" << EOF
\`\`\`

---
EOF
}

# Main execution
main() {
    echo "🔍 Generating dependency documentation..."
    
    # Check if apt-cache is available
    if ! command -v apt-cache &> /dev/null; then
        echo "❌ Error: apt-cache not found. This script requires Debian/Ubuntu system."
        exit 1
    fi
    
    # Update apt cache
    echo "📦 Updating apt cache..."
    sudo apt-get update -qq > /dev/null 2>&1 || true
    
    # Generate header
    echo "📝 Generating documentation header..."
    generate_header
    
    # Process each package
    local total=${#PACKAGES[@]}
    local current=0
    
    for pkg in "${PACKAGES[@]}"; do
        current=$((current + 1))
        echo "[$current/$total] Processing $pkg..."
        add_package_section "$pkg"
    done
    
    # Add footer
    cat >> "$OUTPUT_FILE" << EOF

---

## Notes

- This documentation was automatically generated using \`apt depends\`, \`apt recommends\`, and \`apt suggests\`.
- Some dependencies may have multiple alternatives indicated by \`|\` (OR relationship).
- The actual package versions in the Docker container may differ from the system used to generate this documentation.
- For the most accurate information, build the Docker image and inspect it directly.

---

*Generated by generate-deps-doc.sh*
EOF
    
    echo "✅ Documentation generated: $OUTPUT_FILE"
    echo "📊 File size: $(wc -l < "$OUTPUT_FILE") lines"
}

main "$@"
