ARG BASE_SYSTEM=fedora
ARG BASE_VERSION=44
ARG DESKTOP_TYPE=xfce
ARG DESKTOP_IMAGE_REGION_SUFFIX=
ARG DESKTOP_IMAGE_LABEL=latest
FROM storytellerf/desktop-in-docker:${BASE_SYSTEM}-${BASE_VERSION}-${DESKTOP_TYPE}${DESKTOP_IMAGE_REGION_SUFFIX}-${DESKTOP_IMAGE_LABEL}

ARG OPENJDK_VERSION=21

USER root

RUN dnf install -y \
    java-${OPENJDK_VERSION}-openjdk-devel \
    && dnf clean all
