[program:android]
command=%(ENV_HOME)s/bin/start-android.sh
stdout_logfile=%(ENV_HOME)s/log/supervisor/android_stdout.log
stderr_logfile=%(ENV_HOME)s/log/supervisor/android_stderr.log
autorestart=false
user=%(ENV_SUPERVISOR_USER)s
stopwaitsecs=30
stopasgroup=true
killasgroup=true
