[program:dockerd]
command=sudo /usr/local/bin/dockerd-entrypoint.sh
stdout_logfile=%(ENV_HOME)s/log/supervisor/dockerd_stdout.log
stderr_logfile=%(ENV_HOME)s/log/supervisor/dockerd_stderr.log
autorestart=true
user=%(ENV_SUPERVISOR_USER)s
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true
