services:
  android:
    # Override IMAGE_TAG for non-default JDK providers, for example: debian-trixie-xfce-temurin21-dev-snapshot.
    image: storytellerf/android-in-docker:${IMAGE_TAG:-debian-trixie-xfce-openjdk21-dev-snapshot}
    ports:
      - "6080" # noVNC web interface
      - "5901" # VNC direct connection
      - "5555" # ADB
      - "4723" # Appium
      - "22" # SSH
    volumes:
      - ../../logs:${CONTAINER_HOME:-/home/debian}/log/supervisor
      - ../../data/authorized_keys:${CONTAINER_HOME:-/home/debian}/.ssh/authorized_keys
      - avd_data:${CONTAINER_HOME}/.android/avd
      - sdk_data:${CONTAINER_HOME}/Android/Sdk
      - bash_history:${CONTAINER_HOME}/.desktop-in-docker/.bash_history
      - gradle_data:${CONTAINER_HOME}/.gradle
      - konan_data:${CONTAINER_HOME}/.konan
      - m2_data:${CONTAINER_HOME}/.m2
      - firefox_cache:${CONTAINER_HOME}/.cache/mozilla/firefox
      - firefox_config:${CONTAINER_HOME}/.mozilla/firefox
      - vscode_data:${CONTAINER_HOME}/.vscode
      - vscode_config:${CONTAINER_HOME}/.config/Code

volumes:
  avd_data:
  sdk_data:
    name: sdk_data
    external: true
  bash_history:
  gradle_data:
  konan_data:
  m2_data:
  firefox_cache:
  firefox_config:
  vscode_data:
  vscode_config:
