services:
  android:
    # Override IMAGE_TAG for non-default JDK providers, for example: debian-trixie-xfce-temurin21-dev-snapshot.
    image: storytellerf/android-in-docker:${IMAGE_TAG:-debian-trixie-xfce-openjdk21-dev-snapshot}
    ports:
      - "6080" # noVNC web interface
      - "5901" # VNC direct connection
      - "5555" # ADB
      - "4723" # Appium
      - "22" # SSH
    volumes:
      - ../../logs:${CONTAINER_HOME:-/home/debian}/log/supervisor
      - ../../data/authorized_keys:${CONTAINER_HOME:-/home/debian}/.ssh/authorized_keys
      - gradle_data:${CONTAINER_HOME:-/home/debian}/.gradle
      - konan_data:${CONTAINER_HOME:-/home/debian}/.konan
      - m2_data:${CONTAINER_HOME:-/home/debian}/.m2
      - avd_data:${CONTAINER_HOME:-/home/debian}/.android/avd
      - sdk_data:${CONTAINER_HOME:-/home/debian}/Android/Sdk
      - firefox_cache:${CONTAINER_HOME}/.cache/mozilla/firefox
      - firefox_config:${CONTAINER_HOME}/.mozilla/firefox
      - google_cache:${CONTAINER_HOME:-/home/debian}/.cache/Google
      - google_config:${CONTAINER_HOME:-/home/debian}/.config/Google
      - google_local:${CONTAINER_HOME:-/home/debian}/.local/share/Google
      - gemini_data:${CONTAINER_HOME:-/home/debian}/.gemini
      - antigravity_config:${CONTAINER_HOME:-/home/debian}/.config/Antigravity
      - antigravity_data:${CONTAINER_HOME:-/home/debian}/.antigravity

volumes:
  gradle_data:
    name: gradle_data
    external: true
  konan_data:
  m2_data:
  firefox_cache:
  firefox_config:
  google_cache:
  google_config:
  google_local:
  gemini_data:
  antigravity_config:
  antigravity_data:
