services:
  android:
    image: ${DOCKER_USERNAME:-storytellerf}/android-in-docker:${IMAGE_TAG:-debian-trixie-xfce-openjdk21-snapshot}
    ports:
    - '6080'
    - '5901'
    - '4723'
    - '22'
    - '5555'
    environment:
    - VNC_GEOMETRY=1920x1080
    - VNC_DEPTH=24
    env_file:
    - ../../.env
    volumes:
    - ../../logs:${CONTAINER_HOME:-/home/debian}/log/supervisor
    - ../../data/authorized_keys:${CONTAINER_HOME:-/home/debian}/.ssh/authorized_keys
    - bash_history:${CONTAINER_HOME:-/home/debian}/.desktop-in-docker/.bash_history
    - firefox_cache:${CONTAINER_HOME:-/home/debian}/.cache/mozilla/firefox
    - firefox_config:${CONTAINER_HOME:-/home/debian}/.mozilla/firefox
    - vscode_data:${CONTAINER_HOME:-/home/debian}/.vscode
    - vscode_config:${CONTAINER_HOME:-/home/debian}/.config/Code
    - sdk_data:${CONTAINER_HOME:-/home/debian}/Android/Sdk
    - avd_data:${CONTAINER_HOME:-/home/debian}/.android/avd
    shm_size: 2gb
    restart: unless-stopped
volumes:
  bash_history: null
  firefox_cache: null
  firefox_config: null
  vscode_data: null
  vscode_config: null
  sdk_data: null
  avd_data: null
